import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

import dynamic from 'next/dynamic';

const Game = dynamic(() => import('../components/Game/Game'))


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <div>
        <canvas></canvas>
      </div>

      {  process.browser && <Game /> }

      <footer>

      </footer>
    </>
  )
}

export default Home
