import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Game from '../component/Game/Game'


const Home: NextPage = () => {

  const [ init, setInit ] = useState(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <div>
        <canvas></canvas>
      </div>

      <div>
        {  process.browser && init && <Game /> }
        <button onClick={() => setInit(i => !i)}>Start Game</button>
      </div>

      <footer>

      </footer>
    </div>
  )
}

export default Home
