import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

import dynamic from 'next/dynamic';
import Nav from '../components/Nav/Nav';
import Landing from '../components/Landing/Landing';
import Footer from '../components/Footer/Footer';
import Contact from '../components/Contact/Contact';
import Experience from '../components/Experience/Experience';




const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav/>
      <Landing/>

      <Experience />
      <Contact />
      <Footer />

      
      {/* <div>
        <canvas></canvas>
      </div> */}

     {/*  { process.browser && <Game /> } */}

      
    </>
  )
}

export default Home
